spring.application.name=project
spring.datasource.url=jdbc:mysql://localhost:3306/libdent_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ✅ ถ้าใช้ cookie (JSESSIONID) ผ่าน domain ต่างกัน ต้องระบุ SameSite=None
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
spring.session.redis.configure-action=none
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.timeout=1800


